### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/.github#22]
For tracking/standardizing eslint workflows and scripts

+ [x] lifterlms-advanced-videos
+ [x] lifterlms-stripe
+ [x] lifterlms-custom-fields
+ [x] lifterlms-blocks

**Comment by eri-trabiccolo** [comment]
lifterlms-advanced-videos

**Comment by eri-trabiccolo** [comment]
- [ ] lifterlms-custom-fields

**Comment by thomasplevy** [comment]
ESlint task is updated. The project must use `lint:js` as the NPM script so that the shared lint script will work for all add-ons.

If you find an add-on that needs eslint, it should be added to the workflow sync workflow in this repo at:
https://github.com/gocodebox/.github/blob/4097cdae76b9ac8f89942c7f201f8ca5cb14958f/.github/workflows/workflow-sync.yml#L27-L31
