### ISSUE TITLE
E2E testing

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/.github#23]
Tracking e2e testing workflow updates

**Comment by eri-trabiccolo** [comment]
+ [x] lifterlms-advanced-videos
+ [x] lifterlms-groups
+ [x] lifterlms-blocks

**Comment by thomasplevy** [comment]
Closing with addition of workflow + sync to repos.

If new repos need to be added, they can be listed in this file: https://github.com/gocodebox/.github/blob/ac52befe27560e1592b2177ea0ef6df29177c4f4/.github/workflows/workflow-sync.yml#L31-L35
