### ISSUE TITLE
.editorconfig changes

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/.github#31]
After syncing `.editorconfig` to most of the repositories, I noticed these differences that may need addressing.
1. [`lifterlms-cli`](https://github.com/gocodebox/lifterlms-cli/compare/f7c5443bc049...324e1d01e3b6) used to have `.feature` (shouldn't it have been `feature` without the period?) for Behat files. **Add `feature` extension?**
2. The new version of `.editorconfig`, taken from `lifterlms`, has `yml.template`, but I [couldn't find any files](https://github.com/search?q=org%3Agocodebox++extension%3Atemplate) in any `gocodebox` projects with that extension. **Delete `yml.template` extension?**
3. [`llms-api-node`](https://github.com/gocodebox/llms-api-node/compare/adc009382cf3...a46166728510), [`lifterlms-rest`](https://github.com/gocodebox/lifterlms-rest/compare/db0d25185b4d...1896276a790e) and [`lifterlms-zapier`](https://github.com/gocodebox/lifterlms-zapier/compare/59a6c2d95033...fe954762a29d) had a configuration for `yaml` files. The are many files with this extension. **Add `yaml` extension?**

**Comment by thomasplevy** [comment]
@pondermatic Let's put this on the back burner. We have much more important things to do than audit `.editorconfig` files. I appreciate the consistency you're trying to enforce but I don't have the time to answer these questions right now and you're supposed to be working on bug fixes.
